PROGRAM = SocketConnector

PROGRAM_SRC_DIR = $(PROGRAM_DIR)/source \
				$(PROGRAM_DIR)/source/iperf

EXTRA_COMPONENTS = middleware/printf \
		   middleware/osal \
		   middleware/hifc \
		   middleware/serial \
		   middleware/miniconsole \
		   middleware/altcomlib \
		   middleware/pwrmanager

include ../../../../common.mk
