PROGRAM = SPI

EXTRA_COMPONENTS = middleware/printf \
		   middleware/osal \
		   middleware/hifc \
		   middleware/serial \
		   middleware/miniconsole \
		   middleware/pwrmanager

include ../../../../common.mk
