PROGRAM = Gdma

EXTRA_COMPONENTS = middleware/printf \
		   middleware/osal \
		   middleware/hifc \
		   middleware/serial \
		   middleware/pwrmanager \
		   middleware/miniconsole

include ../../../../common.mk
