PROGRAM = PushWake

EXTRA_COMPONENTS = middleware/printf \
		   middleware/osal \
		   middleware/hifc \
		   middleware/serial \
		   middleware/miniconsole \
		   middleware/pwrmanager \
		   middleware/sensor/accel_lis2dh \
		   middleware/sensor/sensor_lib

include ../../../../common.mk
