PROGRAM = Emux_AtcmdConnector

EXTRA_COMPONENTS = middleware/printf \
		   middleware/osal \
		   middleware/hifc \
		   middleware/serial \
		   middleware/miniconsole \
		   middleware/altcomlib \
		   middleware/emux

include ../../../../common.mk
