PROGRAM = MiscConnector

EXTRA_COMPONENTS = middleware/printf \
		   middleware/osal \
		   middleware/hifc \
		   middleware/serial \
		   middleware/miniconsole \
		   middleware/altcomlib \
		   middleware/sfplogger

include ../../../../common.mk
