PROGRAM = MqttConnector

EXTRA_COMPONENTS = middleware/printf \
		   middleware/osal \
		   middleware/hifc \
		   middleware/serial \
		   middleware/miniconsole \
		   middleware/altcomlib

include ../../../../common.mk
